# Generated by Django 4.2.7 on 2025-10-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyserver',
            name='encryption',
            field=models.CharField(default='AES-256-GCM', max_length=50),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='handshake',
            field=models.CharField(default='RSA-2048', max_length=50),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='vpn_config',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='vpn_type',
            field=models.CharField(choices=[('openvpn', 'OpenVPN'), ('wireguard', 'WireGuard'), ('socks5', 'SOCKS5')], default='openvpn', max_length=20),
        ),
        migrations.AddField(
            model_name='usersession',
            name='assigned_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='interface',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_routing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='vpn_config_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='vpn_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
